## В - 1. Дана целочисленная прямоугольная матрица. Определить: 
### количество строк, не содержащих ни одного нулевого элемента;
### максимальное из чисел, встречающихся в заданной матрице более одного раза.

In [10]:
# Импортируем необходимые библиотеки
import numpy as np

# Объявил матрицу 4х5 и заполнил рандомномными значениями
a = np.random.randint (0, 50, (4, 5))
print(a)

[[37 30  9  4 24]
 [ 3  3 38 10 19]
 [37  7  9 45 42]
 [26  2 42 15 48]]


In [11]:
# Ищу количество строк не содержащих ни одного 0-вого элемента
rows, colums = a[np.where(a.min(axis=1) != 0)].shape
print('Количество строк количество строк, не содержащих ни одного нулевого элемента:', rows)

Количество строк количество строк, не содержащих ни одного нулевого элемента: 4


In [12]:
# Ищу максимальное число, которое встретиться в матрице больше 1 раза
vals, counts = np.unique(a, return_counts=True)
print(max(vals[counts > 1]))

42
